// Mocks generated by Mockito 5.4.6 from annotations
// in parrokit/test/features/community/shell/domain/usecases/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:parrokit/data/models/comment.dart' as _i3;
import 'package:parrokit/data/models/post.dart' as _i2;
import 'package:parrokit/features/community/shell/data/repositories/community_repository.dart'
    as _i4;
import 'package:parrokit/features/community/shell/data/services/community_image_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePost_0 extends _i1.SmartFake implements _i2.Post {
  _FakePost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComment_1 extends _i1.SmartFake implements _i3.Comment {
  _FakeComment_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i4.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Post?> getPostById(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [postId],
        ),
        returnValue: _i5.Future<_i2.Post?>.value(),
      ) as _i5.Future<_i2.Post?>);

  @override
  String generatePostId() => (super.noSuchMethod(
        Invocation.method(
          #generatePostId,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generatePostId,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<_i2.Post> addPost(_i2.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #addPost,
          [post],
        ),
        returnValue: _i5.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #addPost,
            [post],
          ),
        )),
      ) as _i5.Future<_i2.Post>);

  @override
  _i5.Future<void> deletePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePost(
    String? postId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [
            postId,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Post>> getPosts({
    String? postType = 'board',
    int? limit = 10,
    _i7.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
          {
            #postType: postType,
            #limit: limit,
            #startAfter: startAfter,
          },
        ),
        returnValue: _i5.Future<List<_i2.Post>>.value(<_i2.Post>[]),
      ) as _i5.Future<List<_i2.Post>>);

  @override
  _i5.Future<List<_i3.Comment>> getComments(String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValue: _i5.Future<List<_i3.Comment>>.value(<_i3.Comment>[]),
      ) as _i5.Future<List<_i3.Comment>>);

  @override
  _i5.Future<_i3.Comment> addComment(
    String? postId,
    _i3.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            postId,
            comment,
          ],
        ),
        returnValue: _i5.Future<_i3.Comment>.value(_FakeComment_1(
          this,
          Invocation.method(
            #addComment,
            [
              postId,
              comment,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Comment>);

  @override
  _i5.Future<void> deleteComment(
    String? postId,
    String? commentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [
            postId,
            commentId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleCommentLike(
    String? postId,
    String? commentId,
    String? userId,
    bool? isLiked,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleCommentLike,
          [
            postId,
            commentId,
            userId,
            isLiked,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Set<String>> getLikedCommentIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedCommentIds,
          [userId],
        ),
        returnValue: _i5.Future<Set<String>>.value(<String>{}),
      ) as _i5.Future<Set<String>>);

  @override
  _i5.Future<void> incrementViewCount(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #incrementViewCount,
          [postId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleLike(
    String? postId,
    String? userId,
    bool? isLiked,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [
            postId,
            userId,
            isLiked,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleScrap(
    String? postId,
    String? userId,
    bool? isScrapped,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleScrap,
          [
            postId,
            userId,
            isScrapped,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, bool>> getUserPostActions(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPostActions,
          [
            postId,
            userId,
          ],
        ),
        returnValue: _i5.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i5.Future<Map<String, bool>>);

  @override
  _i5.Future<_i2.Post> addQuestion(
    _i2.Post? post,
    String? userId,
    int? requiredCrackers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQuestion,
          [
            post,
            userId,
            requiredCrackers,
          ],
        ),
        returnValue: _i5.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #addQuestion,
            [
              post,
              userId,
              requiredCrackers,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Post>);

  @override
  _i5.Future<void> acceptAnswer({
    required String? postId,
    required String? commentId,
    required String? answererId,
    required int? rewardCrackers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptAnswer,
          [],
          {
            #postId: postId,
            #commentId: commentId,
            #answererId: answererId,
            #rewardCrackers: rewardCrackers,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> votePost(
    String? postId,
    String? userId,
    int? optionIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #votePost,
          [
            postId,
            userId,
            optionIndex,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getMyVotes(
    String? userId,
    List<String>? postIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyVotes,
          [
            userId,
            postIds,
          ],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);
}

/// A class which mocks [CommunityImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityImageService extends _i1.Mock
    implements _i8.CommunityImageService {
  MockCommunityImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> uploadImageToStorage(
    _i9.File? imageFile, {
    required String? userId,
    required String? postId,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageToStorage,
          [imageFile],
          {
            #userId: userId,
            #postId: postId,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> deleteImageFromStorage(String? imageUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteImageFromStorage,
          [imageUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
